### ISSUE TITLE
Unable to scroll horizontally

### ISSUE THREAD

**Issue by AndreasHassing** [scabana/trxviewer#38]
First of all, thank you for this 😃; I was parsing some trx files with my brain and thought: "there is probably an extension for this" and here you are. Awesome 🚀.

I noticed: in the outcome-view, it is not possible to scroll horizontally and reveal the remaining stack trace contents or class name/method name/etc.:

![image](https://user-images.githubusercontent.com/639843/112839210-35fdf380-909e-11eb-8e08-0aed067b7850.png)

Note that there is no horizontal scrollbar, nor does <kbd>Shift</kbd>-<kbd>Scroll</kbd> work.

Edit: found it, [this](https://github.com/scabana/trxviewer/blob/889d02799d9d768647c8f63bd8084053b7e0e2c0/src/frontend/wwwroot/css/app.css#L36) probably just needs to change.

**Comment by scabana** [comment]
Hello,
Thanks for feedback!

Took a look into it, decided to go with a scrollbar per test like so:

![image](https://user-images.githubusercontent.com/8278735/114325211-e20ef800-9afc-11eb-8b2d-dacc0651b3c0.png)

The scrollbar appears much closer to the place where it's needed.
